### ISSUE TITLE
Add command line arguments for puppeteer launch

### ISSUE THREAD

**Issue by austinkelleher** [charlieduong94/mocha-puppeteer#18]
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions

**Comment by tecbeast42** [comment]
+1 without no-sandbox mode it won't run on my linux machines.

**Comment by austinkelleher** [comment]
@tecbeast42 I'll have this ready to go later today.

**Comment by austinkelleher** [comment]
Fixed in `mocha-puppeteer@0.8.2`
