### ISSUE TITLE
Switch to using Express or other HTTP framework

### ISSUE THREAD

**Issue by austinkelleher** [charlieduong94/mocha-puppeteer#27]
Koa only supports Node v7.6.0+

**Comment by austinkelleher** [comment]
Related #12

**Comment by charlieduong94** [comment]
@austinkelleher Do you want to handle this? I can handle the rest of the work needed to get #12 done (I believe have some of the transpliation work already done in another branch somewhere).

**Comment by charlieduong94** [comment]
Fixed via d30f75d
