### ISSUE TITLE
window not defined

### ISSUE THREAD

**Issue by MarcusFulbright** [charlieduong94/mocha-puppeteer#35]
I created a fresh repo with mocha-puppeteer installed. I set up my test.js with the test from the docs:

```
describe('screenshot test', function () {
  it('should take a screenshot', async () => {
    await window.puppeteerCommand({
      type: 'screenshot', // The page command to run
      args: [ {           // The arguments that should be passed to the page command
        path: './test.png'
      } ]
    })
  })
})
```

When I run this test as described in the docs (`./node_modules/mocha/bin/mocha`) I get the following error:

```
1) screenshot test

ReferenceError: window is not defined
at Context.it test.js:3:22
```

I feel like I'm missing a set up step?

**Comment by MarcusFulbright** [comment]
I'm an idiot. Should have been running `./node_modules/mocha-puppeteer/bin/mocha-puppeteer test.js`

**Comment by charlieduong94** [comment]
Glad you got this figured out. If you run into any other issues, let me know.
