### ISSUE TITLE
Access the page object

### ISSUE THREAD

**Issue by MarcusFulbright** [charlieduong94/mocha-puppeteer#36]
is there a way to access the puppeteer page object? I understand I can pass commands through, with window.puppeteerCommand, but is there a way to get an actual page object?

**Comment by charlieduong94** [comment]
Hello @MarcusFulbright, right now accessing the `page` object from within tests is not possible. I don't believe passing down the page object directly to the test page would work (it really only works for primitives and plain json). Just curious, what information do you need to access from it?

**Comment by MarcusFulbright** [comment]
I have classes that describe operations I want to do on a page that require me to pass in the page object. They basically know how to perform any action a user could do on that page.

They could be re-written to return objects that could be passed to window.puppeteerComand, but I'd prefer to avoid that if possible.

**Comment by austinkelleher** [comment]
@MarcusFulbright The entire puppeteer page object cannot be serialized down to the browser as it contains Node.js specific code. Technically, we could expose the `TestRunner` and a `getPage()` function, which could be accessed in Node, but I don't think this will help your use case.

For example, if you run `mocha-puppeteer` in code instead of CLI we could expose the following API:

```js
const mochaPuppeteer = require('mocha-puppteer')

;(async function () {
  const testRunner = await mochaPuppeteer.runTests({ ... })
  const page = testRunner.getPage()
  ...
})()
```

Thoughts?

**Comment by MarcusFulbright** [comment]
currently I'm having to do this:

```
const puppeteer = require('puppeteer');
const login = require('./object_models/login');
let page = null;

describe('test', function () {
    beforeEach(async function() {
        const browser = await puppeteer.launch({headless: false});
        page = await browser.newPage();
    });

    it('should login', async function() {
        await page.goto('http://console.getbuilt.local', {waitUntil: 'networkidle'});
        await login.login(page, '{{USERNAME}}', '{{PASSWORD}}');
    })
});
```

In case you're curious what the login object looks like:

```
async function login(page, username, password) {
    await utility.fillField(page, 'input[name="username"]', username);
    await utility.fillField(page, 'input[name="password"]', password);

    await page.click('button[type="submit"]');
    await page.waitForSelector('i.fa.fa-plus', {visible: true});
    await page.waitForNavigation({waitUntil: 'networkidle'});
}
```

The `utility` functions also take a page and perform actions on it (focuses on the form field and typing in this case).


@austinkelleher I think the code you suggested would allow me to do the same kind of loop that I'm doing now. What I don't understand, is what advantage I'd get from using mocha-puppeteer in this fashion vs just using mocha and handling puppeteer myself?

**Comment by austinkelleher** [comment]
@MarcusFulbright `mocha-puppteer` allows your test files to actually be run in the context of the browser. Your above code is not actually running the tests themselves in the browser. It is running specific code inside of your tests in the context of a browser. Using `mocha-puppteer`, you can manipulate the real DOM through the `window` object as it is running in a real browser context. It's particularly useful for testing UI components. For example, you can perform a real browser render of a UI component (React, Marko, Vue, etc.) and perform assertions on it.

**Comment by MarcusFulbright** [comment]
Ah, I think I understand the difference now. Definitely changes my perspective. I'm going to set aside some time on Monday to try to re-write my current things to reflect this new paradigm. I can see how it would make some things a lot easier for me.

Also, Thanks for all the help. You guys have been awesome!

**Comment by austinkelleher** [comment]
@MarcusFulbright Glad we could help! I'm going to go ahead and close this issue out. Please feel free to ask any additional questions you may have here or open up a new issue.
