### ISSUE TITLE
Consider allowing options to be configured using a .mocha-puppeteer-config file

### ISSUE THREAD

**Issue by charlieduong94** [charlieduong94/mocha-puppeteer#7]
This file would potentially work like a typical `mocha.opts` file, but would also allow for additional `puppeteer` options to be configured.

It may be useful to allow the config to be exported from a js file.

```
module.exports = {
  // options go here
}
```

**Comment by ctnordcl** [comment]
gibs pls

**Comment by charlieduong94** [comment]
It's all yours @ctnordcl

**Comment by ctnordcl** [comment]
So far, I have `index.js` using the `fs` module to check whether `.mocha-puppeteer-config.js` exists, and if it does, making an options object out of a call to require that file as a new module. From there, a destructuring of mochaOptions and puppeteerOptions is made from the required module, and then we can perform logic as needed on a set of options we want for both if them.

**Comment by charlieduong94** [comment]
As we discussed offline, I'll be taking this.
